export const mockListings = [
  {
    id: 1,
    name: "Hotel Lisboa Plaza",
    type: "hotel",
    city: "Lisbon",
    address: "Travessa do Salitre 7",
    safetyScore: 4.8,
    reviewCount: 247,
    pricePerNight: 120,
    image: "/placeholder.svg?height=300&width=400",
    amenities: ["WiFi", "24h Front Desk", "Security Cameras", "Breakfast"],
    isCertified: true,
    tags: ["well-lit", "24h-desk", "safe-neighborhood", "english-speaking"],
  },
  {
    id: 2,
    name: "Casa do Bacalhau",
    type: "guesthouse",
    city: "Lisbon",
    address: "Rua do Grilo 54",
    safetyScore: 4.6,
    reviewCount: 156,
    pricePerNight: 85,
    image: "/placeholder.svg?height=300&width=400",
    amenities: ["WiFi", "Keycard Access", "Female Staff"],
    isCertified: false,
    tags: ["female-staff", "quiet-area", "local-tips"],
  },
  {
    id: 3,
    name: "Barcelona Central Hostel",
    type: "hostel",
    city: "Barcelona",
    address: "Carrer de Pelai 13",
    safetyScore: 4.4,
    reviewCount: 892,
    pricePerNight: 35,
    image: "/placeholder.svg?height=300&width=400",
    amenities: ["WiFi", "Lockers", "Common Area"],
    isCertified: true,
    tags: ["female-dorms", "central-location", "social"],
  },
  {
    id: 4,
    name: "Hotel Casa Fuster",
    type: "hotel",
    city: "Barcelona",
    address: "Passeig de Gràcia 132",
    safetyScore: 4.9,
    reviewCount: 324,
    pricePerNight: 280,
    image: "/placeholder.svg?height=300&width=400",
    amenities: ["WiFi", "Concierge", "Spa", "Restaurant"],
    isCertified: true,
    tags: ["luxury", "safe-area", "excellent-staff"],
  },
  {
    id: 5,
    name: "Lloyd Hotel",
    type: "hotel",
    city: "Amsterdam",
    address: "Oostelijke Handelskade 34",
    safetyScore: 4.7,
    reviewCount: 445,
    pricePerNight: 150,
    image: "/placeholder.svg?height=300&width=400",
    amenities: ["WiFi", "Restaurant", "Bike Rental"],
    isCertified: false,
    tags: ["unique-design", "waterfront", "bike-friendly"],
  },
]

export const mockReviews = [
  {
    id: 1,
    listingId: 1,
    userId: 1,
    userName: "Emma Thompson",
    date: "2024-01-15",
    overallScore: 4.8,
    scores: {
      neighborhood: 4.5,
      security: 5.0,
      staff: 4.8,
      accessibility: 4.6,
    },
    tags: ["well-lit", "24h-desk", "safe-neighborhood"],
    text: "Felt completely safe during my 4-night stay. The hotel is in a great location with well-lit streets. The 24-hour front desk staff were incredibly helpful and spoke excellent English. The neighborhood felt very safe even when walking alone at night.",
    helpfulCount: 23,
  },
  {
    id: 2,
    listingId: 1,
    userId: 2,
    userName: "Sophie Chen",
    date: "2024-01-08",
    overallScore: 4.6,
    scores: {
      neighborhood: 4.3,
      security: 4.8,
      staff: 4.7,
      accessibility: 4.6,
    },
    tags: ["keycard-access", "helpful-staff"],
    text: "Great hotel for solo female travelers. The keycard access system made me feel secure, and the staff went out of their way to provide local safety tips. Only minor issue was some street noise at night.",
    helpfulCount: 18,
  },
  {
    id: 3,
    listingId: 2,
    userId: 3,
    userName: "Maria Santos",
    date: "2024-01-12",
    overallScore: 4.4,
    scores: {
      neighborhood: 4.2,
      security: 4.5,
      staff: 4.8,
      accessibility: 4.1,
    },
    tags: ["female-staff", "local-tips", "quiet-area"],
    text: "Lovely guesthouse with amazing female staff who really understood solo travel concerns. They provided excellent local recommendations and the area felt safe. The only downside was the slightly tricky location to find initially.",
    helpfulCount: 15,
  },
]

export const mockCommunityPosts = [
  {
    id: 1,
    userId: 1,
    userName: "Emma Thompson",
    destination: "Lisbon",
    title: "Safest way from LIS airport to city center at night?",
    body: "Landing at 11 PM next week - what's the safest transport option for a solo female traveler?",
    date: "2024-01-20",
    replies: 8,
    tags: ["transport", "airport", "night-travel"],
  },
  {
    id: 2,
    userId: 2,
    userName: "Sophie Chen",
    destination: "Barcelona",
    title: "Female-only gym recommendations in Eixample?",
    body: "Looking for women-only fitness facilities or classes in the Eixample district. Any suggestions?",
    date: "2024-01-19",
    replies: 5,
    tags: ["fitness", "women-only", "eixample"],
  },
]
